export const Login = () => import('@/views/Auth/LoginView.vue')
export const ChangePassword = () => import('@/views/Auth/ChangePasswordView.vue')
export const ForgotPassword = () => import('@/views/Auth/ForgotPasswordView.vue')
export const ResetPassword = () => import('@/views/Auth/ResetPasswordView.vue')
export const NotFound = () => import('@/views/NotFound/NotFoundView.vue')
export const Home = () => import('@/views/Home/HomeView.vue')
